# Makefile config

# Compiler

CC = g++
CXXFLAGS = -std=c++11 -O3 -Wall
LDFLAGS = 

# app

CORE = ./core
MAIN = solver

# make dependencies

DEPH = \
    $(CORE)/timing.h \
    $(CORE)/unpair.h \
    $(CORE)/graph.h \
    $(CORE)/fas.h \
    $(CORE)/gio.h
DEPCPP = \
    $(CORE)/graph.cpp \
    $(CORE)/fas.cpp \
    $(CORE)/gio.cpp